services:
  nginx:
    image: nginx:latest
    container_name: sistema_login_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_net

  php:
    build:
      context: ./docker/php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: sistema_login_php_fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_net

  mariadb:
    image: mariadb:11
    container_name: sistema_login_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_login
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_login_phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - app_net

volumes:
  mariadb_data:

networks:
  app_net:
    driver: bridge
